### ISSUE TITLE
Consider GitHub app to assist with reviewing ipynb changes

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/orkg-lsuc-jn#5]
When I saw the #4's diff just now, I remembered [ReviewNB](https://www.reviewnb.com/) and though it might be useful for you here, and for [orkg-npfe-jn](https://github.com/TIBHannover/orkg-npfe-jn). Cheers!

**Comment by katrinleinweber** [comment]
@markusstocker: What do you think? Shall I install it or do you want to?

**Comment by markusstocker** [comment]
Katrin, please go ahead ... waiting for me is no longer a good strategy. :/

**Comment by katrinleinweber** [comment]
OK, done: https://app.reviewnb.com/TIBHannover/
